name: Playwright Tests

on:
  pull_request:
    branches: ['**']

jobs:
  playwright-run:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-noble

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      USERNAME1: ${{ secrets.USERNAME1 }}
      PASSWORD1: ${{ secrets.PASSWORD1 }}
      CI: "true"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test