name: Playwright Tests

on:
  pull_request:
    branches: ['**']

jobs:
  playwright-run:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy

    env:
      BASE_URL: "https://qauto.forstudy.space/"
      USERNAME1: "guest"
      PASSWORD1: "welcome2qauto"
      CI: "true"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test